### PR TITLE
8334475: UnsafeIntrinsicsTest.java#ZGenerationalDebug assert(!assert_on_failure) failed: Has low-order bits set

### PR DESCRIPTION
**Pull request by swesonga**
The implementation of the pd_conjoint_jlongs_atomic function in the Windows AArch64 port calls pd_conjoint_oops_atomic to copy jlongs from the source to the destination. However, when CHECK_UNHANDLED_OOPS is defined, the copying of each jlong in pd_conjoint_oops_atomic calls oop::operator= instead of just copying the jlong.
oop::operator= then treats the value to be copied as a pointer, causing the assertion failure in [JDK-8334475](https://bugs.openjdk.org/browse/JDK-8334475). The fix is to directly copy the jlongs from the source to the destination.

### CODE REVIEW

**Review by JohnTortugo — APPROVED** [review]
Looks like there is some pressure to fix this asap, so LGTM. 

However, I think we should create a follow up RFE to remove the (existing & new) duplicated code. Looks like the x86 port had a refactor a few years ago (probably after creating of aarch64 port) to remove such code duplication. Maybe we can do something similar to what was done in x86.

**Review by brianjstafford — APPROVED** [review]
LGTM

**Comment by brianjstafford** [comment]
> Looks like there is some pressure to fix this asap, so LGTM.
> 
> However, I think we should create a follow up RFE to remove the (existing & new) duplicated code. Looks like the x86 port had a refactor a few years ago (probably after creating of aarch64 port) to remove such code duplication. Maybe we can do something similar to what was done in x86.

I think this is a good suggestion.

**Comment by macarte** [comment]
This is cpp code so a template method would work, you can still cast to similar types to reduce generated code

**Pull request closed without merging**
